### ISSUE TITLE
De automatische deploy of vernieuwing werkt niet (voor alle pagina's)

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/erfgoed-en-locatie.github.io#3]
De wijzigingen voor deze pagina komen niet door:
http://erfgeo.nl/tools/histodraw.html

(Heb er gisteren 3 oude kaarten aan toegevoegd en css fixes gedaan (legenda ding zou rechtsonder moeten staan).

**Comment by wires** [comment]
don't know, `jekyll server --baseurl '' --port 4001` output looks fine

```
Configuration file: /Users/jelle/r/erfgoed-locatie/erfgoed-en-locatie.github.io/_config.yml
            Source: /Users/jelle/r/erfgoed-locatie/erfgoed-en-locatie.github.io
       Destination: /Users/jelle/r/erfgoed-locatie/erfgoed-en-locatie.github.io/_site
      Generating...
                    done.
 Auto-regeneration: enabled for '/Users/jelle/r/erfgoed-locatie/erfgoed-en-locatie.github.io'
Configuration file: /Users/jelle/r/erfgoed-locatie/erfgoed-en-locatie.github.io/_config.yml
    Server address: http://127.0.0.1:4001/
  Server running... press ctrl-c to stop.
```

When I look in the generated files I see the content of your commits... ask github?

**Comment by wires** [comment]
also, link to Leaflet CDN is wrong `https://d591zijq8zntj.cloudfront.net/leaflet-0.7.3/leaflet.css` ~> 404

**Comment by monikalechner** [comment]
Geldt dit ook voor de /over-ons pagina? En wanneer worden de problemen verholpen?

**Comment by wires** [comment]
Hmm, I looked into this and tried to push a new commit, but page doesn't seem to update.

I don't have more time to look into this now, maybe @w0ps can look into this?

https://help.github.com/articles/troubleshooting-github-pages-build-failures/

I've tested with jekyll v 2.5.3, [github runs 2.4.0](https://pages.github.com/versions/) maybe that's a problem?

@monikalechner yes it's affected, but you can keep updating the files, eventually someone should get this to work

**Comment by monikalechner** [comment]
@wires yes, thanks for the update! someone should ineed. ;-) It's not extremly urgent, as all of you know. Would be nice to have online by the beginning of next week! Cheers!

**Comment by phpetra** [comment]
@wires: Indeed, the pages do not seem to update...

@w0ps: maybe you can also fix the broken leaflet link, mentioned above?

**Comment by Ivokato** [comment]
Ik krijg m helaas ook niet zo ver dat ie update, en ik heb geen idee waarom. Krijg geen foutmelding.
als ie zou updaten zou ik de leaflet link fixen (die het bij mij wel doet)

hopelijk kan @bertspaan helpen met debuggen? Niet het meest inspirerende klusje maar ik heb geen aanknopingspunten

**Comment by wires** [comment]
also, we can ask github!

**Comment by bertspaan** [comment]
Ik kan helemaal nergens mee helpen de komende tijd want m'n harde schijf is kapot gegaan en m'n laptop doet niets meer... Ga zo proberen nieuwe HD te kopen, en kijken of ik nog iets kan redden, maar ik zit een beetje hier met m'n handen in m'n haar :weary:

**Comment by Ivokato** [comment]
ja shit ik hoorde het, sterkte!

2015-06-09 22:07 GMT+02:00 Bert Spaan notifications@github.com:

**Comment by Ivokato** [comment]
Ok is opgelost:

master branch gebruiken (omdat het een organisatie pagina is)
CNAME file terug gezet (die was weg)
groetjes
