### ISSUE TITLE
histodraw app doesn't work (CDN issue)

### ISSUE THREAD

**Issue by wires** [erfgoed-en-locatie/erfgoed-en-locatie.github.io#4]
![screen shot 2015-06-15 at 22 20 22](https://cloud.githubusercontent.com/assets/315734/8169898/e4c48c8c-13ac-11e5-9144-0a586ec20805.png)

Histodraw doesn't work on `erfgeo.nl`, I think because people working on master branch, not gh-pages. you can change the default branch in repo settings.

Anyway, it fails loading `leaflet` from CDN, remember this being fixed before

**Comment by phpetra** [comment]
Must be your browser cause over here it's looking perfectly fine....
![screen shot 2015-06-15 at 22 27 20](https://cloud.githubusercontent.com/assets/2119144/8170002/d6c8b99a-13ad-11e5-9190-72bcdd6c2999.png)

**Comment by wires** [comment]
cool! werkt wel in private mode.. maar raar? geen blockers nada

**Comment by jobspierings** [comment]
ziet er erg mooi uit!
