### ISSUE TITLE
histodraw werkt niet

### ISSUE THREAD

**Issue by wires** [erfgoed-en-locatie/erfgoed-en-locatie.github.io#7]
http://erfgeo.nl/tools/histodraw.html

![screen shot 2015-06-29 at 12 39 00](https://cloud.githubusercontent.com/assets/315734/8406372/e1fe37a0-1e5b-11e5-9af3-e03a464fa304.png)

krijg 404 op https://d591zijq8zntj.cloudfront.net/leaflet-0.7.3/leaflet.js en daardoor `L` is not defined

**Comment by phpetra** [comment]
Hier werkt het prima... is dat weer een blokkende browser-plugin?

**Comment by Ivokato** [comment]
die cdn is soms down denk ik, missch ff een lokale versie van die missende
library inpluggen?

2015-07-15 21:10 GMT+02:00 Petra Dreiskämper notifications@github.com:

**Comment by phpetra** [comment]
Inmiddels gefikst
