### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by jobspierings** [erfgoed-en-locatie/erfgoed-en-locatie.github.io#8]
Shouldn't this repo be renamed to 

> https://github.com/erfgoed-en-locatie/ **erfgeo.nl**

since this repo does _not_ contain the erfgoed en locatie website?

**Comment by wires** [comment]
Nope, sadly this name is "magical": it _has_ to be called `[organization].github.io` in order to function as github pages repo... (more or less)

**Comment by wires** [comment]
Oh, btw. usually it's a good idea to let the submitter of an issue close it when (s)he thinks his/her problem is solved. For instance, you might want to put extra notice here that it involves the erfgeo.nl website... (it's in the CNAME file, but anyway...)
